title: Higher-Order Motif Counting and Clustering
description: This site serves as the webpage for our group's (Dylan Lee, Jonathan Li, Karthikeya Manchala, Matthew Wilson) project.
github_username:  dylanknlee

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
gem "github-pages", group: :jekyll_plugins
plugins:
  - jekyll-feed
  - jekyll-remote-theme
